FROM tomcat:9.0-jdk17

# Clear default webapps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy WAR file generated by Maven into webapps
COPY Amazon/target/Amazon.war /usr/local/tomcat/webapps/ROOT.war

CMD ["catalina.sh", "run"]

